### PR TITLE
domain_word returns incorrect value while locale is set to 'ru'

### PR DESCRIPTION
**Pull request by b264**
Faker::Internet.email generates email without domain name https://github.com/stympy/faker/issues/247

### CODE REVIEW

**Comment by b264** [comment]
https://github.com/stympy/faker/issues/297 https://github.com/stympy/faker/pull/248

**Comment by asiniy** [comment]
+1

**Comment by b264** [comment]
inlcuded in 1.7.3

**Comment by b264** [comment]
@Vorob-Astronaut @danil @project-eutopia @maksimf @solutus @EugZol @Makapoxa

**Pull request merged**
