### PR TITLE
Slack emoji

### PR DESCRIPTION
**Pull request by NikitaAvvakumov**

### CODE REVIEW

**Comment by b264** [comment]
@morozgrafix Thank you for your contribution!

**Comment by morozgrafix** [comment]
@theB264 happy to help

**Comment by morozgrafix** [comment]
@NikitaAvvakumov and @theB264 thanks for fixing the tests. missed that one with `:e-mail:`. We have recently added a `:pride:` custom emoji and I've made an update to pull request on original faker repo. https://github.com/stympy/faker/pull/351

**Comment by NikitaAvvakumov** [comment]
@morozgrafix Glad to help. We'll be happy to add `:pride:` to our fork, I'll create a PR shortly.

Hope your efforts get acknowledged by the Faker people. In the meantime, feel free to give FactoryHelper a shot :) We're still in pre-release stage, but working on new functionality that we think will improve and expand the gem significantly. A big chunk of that will be based on lingering Faker PRs like yours.

**Comment by morozgrafix** [comment]
@NikitaAvvakumov Great! Thanks. I already substituted faker with factory-helper in my project and I do appreciate you guys keeping it up to date.

**Pull request merged**
