### PR TITLE
Updated Slack Emoji

### PR DESCRIPTION
**Pull request by morozgrafix**
Removed Categories:
 - `celebration`
 - `objects_and_symbols`

Added Categories:
 - `objects`
 - `symbols`
 - `flags`

Deprecated Methods:
 - `FactoryHelper::SlackEmoji.celebration`
 - `FactoryHelper::SlackEmoji.objects_and_symbols`

New Methods:
 - `FactoryHelper::SlackEmoji.objects`
 - `FactoryHelper::SlackEmoji.symbols`
 - `FactoryHelper::SlackEmoji.flags`

### CODE REVIEW

**Comment by morozgrafix** [comment]
Travis seems to be failing due to unrelated errors. Not sure why coverage went down as well. I'm open to suggestions on improvements.
I'm also planning on adding other languages that Slack supports now.

**Comment by b264** [comment]
Some of these changes are not backwards-compatible, were you wanting a 2.0 version?

**Comment by morozgrafix** [comment]
I wasn't sure what the process of deprecating methods for this Gem. I think there are a few of options that can work. 
1. Show deprecation warning for `FactoryHelper::SlackEmoji.celebration` and `FactoryHelper::SlackEmoji.objects_and_symbols`
2. Stub it out with picking emoji from another category (silently) - not ideal but backwards compatible
3. Do both 1 and 2

Let me know if there is a good way to deprecate methods.

**Comment by b264** [comment]
I would do 1
```ruby
warn '[DEPRECATION] "Class.method" is deprecated.  Please use "Class.method" instead.'
```
and 2 both

**Comment by morozgrafix** [comment]
@b264 I believe that it should be backwards compatible now with deprecation warnings for those methods. Test output is kind of ugly now though :(

**Comment by b264** [comment]
I'm not sure why 2 of the tests failed, but it's not related to this code, it seems

**Comment by b264** [comment]
[Rebuilt master](https://travis-ci.org/factory-helper/factory-helper/builds/98845353) and it's green.  The failure has to be something here.  Can't imagine what it is.  Maybe `warn` ?

**Comment by morozgrafix** [comment]
I ran it twice on Travis and both times it passed with flying colors for all ruby versions with exception of the 2.4.1 (I think there is some compatibility issues with dependencies and that version of ruby). Here is a link https://travis-ci.org/morozgrafix/factory-helper/builds/297398785 

I quickly looked at logs for failing runs triggered by PR and it looks like gem failed to install correctly.

**Comment by b264** [comment]
Released as [1.8.0](https://github.com/factory-helper/factory-helper/releases/tag/v1.8.0)

**Pull request merged**
