### PR TITLE
Add RSpec

### PR DESCRIPTION
**Pull request by NikitaAvvakumov**
- default Rake task runs Test::Unit & RSpec, then sends combined
  coverage data to Coveralls
- RSpec: `before(:suite)` & `after(:each)` hooks set `Faker::Config.locale = nil` to
  prevent carryover of state between examples. Tested in rspec_locale_hooks_spec.rb
- all rake tasks consolidated in Rakefile

### CODE REVIEW

**Comment by NikitaAvvakumov** [comment]
Running specs, either alone or together with Test::Unit gives `gems/simplecov-0.10.0/lib/simplecov/defaults.rb:50: warning: global variable '$ERROR_INFO' not initialized` warning at the end. This seems to affect no functionality as far as I see, but I'll try to fix it.

**Comment by NikitaAvvakumov** [comment]
I've gotten nowhere with that warning. Google only returns links to other people's Travis runs where the same warning was raised.

**Comment by b264** [comment]
This looks good.  I'm not seeing the `$ERROR_INFO` warning.

**Comment by NikitaAvvakumov** [comment]
Odd, because it shows up on Travis too https://travis-ci.org/factory-helper/factory-helper/jobs/62906845#L158. Anyway, I'm removing the [WIP]

**Comment by b264** [comment]
:shipit:

**Pull request merged**
